name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: printArray
      id: printarray
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: printArray
        setup-command: ''
        command: make test try=printArray
        timeout: 10
        max-score: 1
    - name: replaceVariable
      id: replacevariable
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: replaceVariable
        setup-command: ''
        command: make test try=replaceVariable
        timeout: 10
        max-score: 1
    - name: sumOdds
      id: sumodds
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: sumOdds
        setup-command: ''
        command: make test try=sumOdds
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PRINTARRAY_RESULTS: "${{steps.printarray.outputs.result}}"
        REPLACEVARIABLE_RESULTS: "${{steps.replacevariable.outputs.result}}"
        SUMODDS_RESULTS: "${{steps.sumodds.outputs.result}}"
      with:
        runners: printarray,replacevariable,sumodds
